### ISSUE TITLE
generar qr con lista de candidatos y llave pública

### ISSUE THREAD

**Issue by camilog** [camilog/moca-administrator-app#11]
necesario para la fácil configuración de ballot-selection y ballot-verification

**Comment by diegodi** [comment]
Ya genera código, falta verificar que esté bien hecho.

**Comment by diegodi** [comment]
El QR no se está generando de manera correcta, debo seguir revisando para que lo genere bien.

**Comment by diegodi** [comment]
Solucionado al generar dos qr diferentes, uno que contiene la lista de candidatos y el segundo que contiene la llave pública.
